### ISSUE TITLE
Integrate kgt?

### ISSUE THREAD

**Issue by ArthurSonzogni** [ArthurSonzogni/Diagon#10]
What about integrating [kgt](https://github.com/katef/kgt) into [Diagon](https://arthursonzogni.com/Diagon/#code_area)?
This would allow people to use kgt online & interactively.

I can totally see myself using it. For instance when implementing [CSP](https://www.w3.org/TR/CSP3/#grammardef-path-part) in [Chrome](services/network/public/cpp/content_security_policy/content_security_policy.cc) or just for fun.

I will take a look. I should be quite easy since this is C code. I just need to rewrite Makefile into a CMake file.

+CC: @katef FYI

**Comment by ArthurSonzogni** [comment]
Almost done.I integrated [kgt](https://github.com/katef/kgt) into [Diagon](https://arthursonzogni.com/Diagon/#code_area)
Everything seems to work. This is really nice!
+CC: @katef FYI

You can try this online: https://arthursonzogni.com/Diagon

Tools > "Grammar (kgt - experimental)"

**Comment by katef** [comment]
Oh wow! This is great! It looks like you did a really good job, with all the various output formats. Thanks!
