### ISSUE TITLE
I made a Vim plugin wrapping Diagon's API

### ISSUE THREAD

**Issue by willchao612** [ArthurSonzogni/Diagon#24]
Hi, thanks for this useful tool!

I am a Vim/Neovim user and I draw simple diagrams in markdown from time to time. When I met Diagon I wonder if I can integrate it into my workflow, so I made a Vim plugin named [vim-diagon](https://github.com/willchao612/vim-diagon) wrapping Diagon's API. It is pretty bare bone but it improves my workflow. You can give it a try if you want.

Thanks again!

**Comment by ArthurSonzogni** [comment]
Wow really nice!

I made the command line version, so that such tools could emerge. I remember in 2019, I wanted to use it in vim:
https://www.youtube.com/watch?v=WTnMft_wvZU

Thanks for this plugin! We should talk about it in the README of Diagon. I will try to do it this evening.

**Comment by ArthurSonzogni** [comment]
I added a link toward your repository. Thanks again!

**Comment by ArthurSonzogni** [comment]
Thanks again!
It is referenced in the README. I think I should close this issue now.
