### ISSUE TITLE
I made vscode extension using Diagon API

### ISSUE THREAD

**Issue by ElmouradiAmine** [ArthurSonzogni/Diagon#25]
Hi Arthur !
I found out that your tool could be really useful for us programmers. In fact, this tool will allow us to put better comments by adding diagrams, mathematical expressions and much more! I have compiled your API to webassembly and I created a javascript library wrapper that I published to npm.  I was able to use that library  in my [vscode extension ](https://github.com/ElmouradiAmine/vscode-diagon). I'll publish this extension soon in the vscode marketplace !
I hope you liked it!
Thank you for this tool !
![screencast](https://i.imgur.com/ZmdLGrL.gif)

**Comment by ArthurSonzogni** [comment]
I added a link toward your repository. Thanks again!

**Comment by ArthurSonzogni** [comment]
Thanks again!
It is referenced in the README. I think I should close this issue now.
