### ISSUE TITLE
Missing uuid module (in antlr dependencies)

### ISSUE THREAD

**Issue by tg-m** [ArthurSonzogni/Diagon#26]
There is a problem with missing `uuid` module, which cannot be successfully found by `pkg-config` during `antlr` dependencies resolving.

The error log:

```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'uuid'
--   No package 'uuid' found
```

This can be fixed by installing `uuid-dev` package on Ubuntu (tested on Ubuntu 18.04.1 LTS, Xubuntu flavour actually), should also work on Debian.

For those who look only for code snippets:
```bash
sudo apt-get install uuid-dev
```

**Can be marked as resolved.**

I've added this issue mainly because grepping for `uuid.h` in `antlr` dependencies and reverse searching this file in using `apt-file` might not be obvious for everyone.

**Comment by ArthurSonzogni** [comment]
Thanks for letting me know!

I added some warning in the README.
