### ISSUE TITLE
missing build instructions 

### ISSUE THREAD

**Issue by jbauernberger** [ArthurSonzogni/Diagon#27]
this is a phenomenal project. A few hints about compiling from source that might be useful:

On Debian / Ubuntu you will need boost (in addition to `uuid-dev`) otherwise the build fails:

`sudo apt install libboost1.71-dev`

then:

```
mkdir build && cd build 
cmake ..
make -j
sudo make install
```

**Comment by ArthurSonzogni** [comment]
That's a good thing to do. I will.

**Comment by ArthurSonzogni** [comment]
I addressed this suggestion. Thanks!
