### ISSUE TITLE
Crash with invalid input

### ISSUE THREAD

**Issue by ppiecuch** [ArthurSonzogni/Diagon#36]
```
pawelp@pawelp-mb-13 fltk % echo "1/2=" | ../../../Diagon/build-osx/diagon Math
line 1:4 mismatched input '\n' expecting {STRING, '(', '{', '[', '+', '-', VARIABLE}
zsh: done                echo "1/2=" |
zsh: segmentation fault  ../../../Diagon/build-osx/diagon Math
```

Is there a way I could managed invalid input? I am writing gui plugin and I am not able to catch these kind of crashes.

Regards
Pawel

**Comment by ArthurSonzogni** [comment]
Not crashing is a much reasonable way to handle this. I agree. This would require some code change.
