### ISSUE TITLE
Can this convert a mathematical equation written in latex to ascii?

### ISSUE THREAD

**Issue by sujaldev** [ArthurSonzogni/Diagon#44]
Sorry this isn't an issue but since discussions aren't enabled I didn't know where to ask this.

I have equations in latex but I'm not sure how to convert it to the syntax used by Diagon, any suggestions on how to approach this?

**Comment by ArthurSonzogni** [comment]
Welcome!

> Sorry this isn't an issue but since discussions aren't enabled I didn't know where to ask this.

Discussion opened: https://github.com/ArthurSonzogni/Diagon/discussions

> I have equations in latex but I'm not sure how to convert it to the syntax used by Diagon, any suggestions on how to approach this?

We support converting diagon syntax toward multiple target:
- Latex
- Ascii art
- Unicode art

However, this doesn't work in the other direction. Parsing latex would be too difficult.

**Comment by sujaldev** [comment]
I think I've found [another tool](https://github.com/Pomax/tex2utf/) that probably does what I'm trying to achieve, thank you for your response!
