### ISSUE TITLE
Support "freeform" flowcharts

### ISSUE THREAD

**Issue by pinpox** [ArthurSonzogni/Diagon#52]
Couldn't come up with a better name, I would like to draw diagrams like this:
![](https://cdn.berkeleygraphics.com/static/images/marketing/box-drawing-diagram.svg)

I there any possiblity to do this with diagon or could that be implemented? The diagram above is made with Monodraw, which does not have Linux support and. It would be great if Diagon could be used for this, I'm looking for a tool to create this kind of diagrams for docs and architectural overviews for software.

**Comment by ArthurSonzogni** [comment]
Diagon is more about a `markdown-like` => `Ascii/Unicode` tool.
Here, your need looks more like an ascii drawing tool. I don't believe this is a good fit. However, it might be an interesting side project.

**Comment by nkh** [comment]
@pinpox https://github.com/nkh/P5-App-Asciio (that I wrote), may be what you are looking for. It's a Gtk/linux application, there's a (good) prototype TUI too.
