### ISSUE TITLE
Limes in Mathematical expression

### ISSUE THREAD

**Issue by KingaMasz** [ArthurSonzogni/Diagon#56]
Would it be possible to support limes in Mathematical expression? I was trying to write something like: lim_{n -> infinity} 1/n but there was error with symbol ">" and everything after "lim_{n -> infinity}".

In my opinion it should generate output similar to this:
             1
  lim      --
n->∞    n

**Comment by ArthurSonzogni** [comment]
It would be nice! Thanks for suggesting this.

**Comment by ArthurSonzogni** [comment]
Fixed (I think)
