### ISSUE TITLE
New lines in Tree

### ISSUE THREAD

**Issue by KingaMasz** [ArthurSonzogni/Diagon#58]
Would it be possible to ignore additional new lines within one tree?
Like in this example:
parent
 child1

 child2

child1 and child2 are in the same tree but the output looks like:
parent
 `-child1

 `-child2

In my oponion empty lines between them should be ignored for better looking tree, like this:
parent
 -child1
 -child2

**Comment by ArthurSonzogni** [comment]
Good ideas! Thanks!
