### ISSUE TITLE
Support for comments

### ISSUE THREAD

**Issue by eleijonmarck** [ArthurSonzogni/Diagon#64]
I love this tool and would love to support comments in the actual text and not the rendered output. Is this possible?

**Comment by ArthurSonzogni** [comment]
Hi!

The FlowChart on support comments.
https://arthursonzogni.com/Diagon/#Flowchart

I guess we can also add support for other tools too. In particular the sequence one.

**Comment by ArthurSonzogni** [comment]
This has been fixed. I will update the website soon to reflect the change.
