### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by talos-vulndev** [ArthurSonzogni/Diagon#65]
Hello, the Cisco Talos team found a security vulnerability affecting Diagon. As this is a sensitive security issue, this message is to request a PGP key for further communication. Please acknowledge receipt of this message by email to vulndiscovery@external.cisco.com

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. https://tools.cisco.com/security/center/resources/vendor_vulnerability_policy.html Please CC vulndiscovery@external.cisco.com on all correspondence related to this issue.

**Comment by ArthurSonzogni** [comment]
Hello, thanks for reporting bugs.

Instead of using PGP, you can also use github:
https://github.com/ArthurSonzogni/Diagon/security/advisories/new

My PGP keys are:
https://keyserver.ubuntu.com/pks/lookup?op=get&search=sonzogniarthur@gmail.com
I will send an email, as you asked.

**Comment by ArthurSonzogni** [comment]
Fixed in [v1.1.158](https://github.com/ArthurSonzogni/Diagon/releases/tag/v1.1.158)
See the two CL above.

I released the new version. I rolled out the new version as "stable" in linux snap. This should update the ~80 existing users. 

I ran the fuzzer for a long time and did not find anything new.
