### ISSUE TITLE
Sequence: a way to make a visual difference between async and sync calls

### ISSUE THREAD

**Issue by bjornstromberg** [ArthurSonzogni/Diagon#68]
as i wrote in issue #63 a way to quickly see if a sequence call is async or sync would be a great enhancement.

as an example solid lines would be sync, and for example dashed lines would be async. 

as things are now i use '(as)' in the line message to denote the async calls but it clutters the view for such a simple thing as a dashed line would solve.

its a great tool so far.

**Comment by ArthurSonzogni** [comment]
What about something like:
```k
->  : arrow
--> : dashed arrow
```

I wonder how to represent them both, in both ascii-only and unicode versions.

**Comment by bjornstromberg** [comment]
absolutely that would work in the 'input' format.

i would probably represent them the same way they are now,
just that the dashed ones, if required to be spaced apart to make it visible they are different. 

another way, would be using color coding by specifying the requested color pair, with a default set like dark-grey / light-grey or anything that should work on most terminals (usually black background)

color coding will likely be a larger breaking change for a lot of components.

**Comment by ArthurSonzogni** [comment]
I think we can close this, thanks to #69
