### ISSUE TITLE
Use 'v' instead of '▽'

### ISSUE THREAD

**Issue by rentruewang** [ArthurSonzogni/Diagon#75]
Use of ▽ always cause problems on Github. (and my editor which is vscode).

Is it possible for there to be a configuration where it uses 'v' instead? This has the benefit of being a normal ascii character so monospace fonts are guaranteed to space it correctly.

Thank you for reading!

**Comment by ArthurSonzogni** [comment]
There is a "ascii-only" option for the ["GraphPlanar"](https://arthursonzogni.com/Diagon/#GraphPlanar) tool. Do you mean adding the same for ["GraphDAG"](https://arthursonzogni.com/Diagon/#GraphDAG)?

**Comment by rentruewang** [comment]
@ArthurSonzogni Yes that would be helpful. However, I think the problem is more about `▽` having a different width rather than enforcing ascii. (See below)

```
▽▽▽▽▽
aaaaaa
vvvvvv
```

**Comment by leshabirukov** [comment]
Why is it closed?
Issue still remains, see flowchart from online tool:

<img width="692" height="167" alt="Image" src="https://github.com/user-attachments/assets/b8d6e394-35b2-4209-ad10-9b29a6508e9b" />

**Comment by ArthurSonzogni** [comment]
@leshabirukov 
There is no "ascii" only option for the "FlowChart (Work in progress) so far.
