### ISSUE TITLE
CLI option?

### ISSUE THREAD

**Issue by Pomax** [ArthurSonzogni/Diagon#8]
Hiya, for... reasons... I tried loading up https://pomax.github.io/bezierinfo in Lynx, and realised that it would be very nice to see an ascii version of the ~250 LaTeX formulae pepper throughout the page, rather than seeing this:

![image](https://user-images.githubusercontent.com/177243/94998910-5d01bf80-056a-11eb-8823-b7c5753798ea.png)

Is there a way to invoke Diagon via the CLI, so it can be made part of a build chain, calling it on a .tex file and getting stdio output that can be used by "whatever was looking at stdio"?

E.g. I currently generate those svg images by effectively running `xelatex 1a2b3c4d.tex && pdfcrop 1a2b3c4d.pdf && pdf2svg 1a2b3c4d-cropped.pdf && svgo 1a2b3c4d-cropped.svg && cp 1a2b3c4d-cropped.svg ../images/latex/1a2b3c4d.svg` so create a secondary chain that runs Diagon would be _super_ cool.

**Comment by ArthurSonzogni** [comment]
Yes there is a CLI. I should definitely mention this in the README.

Diagon is written in C++.

Note: The Math module takes formula written in its own simple language (as close a natural one) and can output formula in ascii art, unicode and latex.

Note that it can **output** latex, but not take latex as **input**.

You can compile yourself the executable from source, or use the precompiled version (using snap)
https://snapcraft.io/diagon
```bash
sudo snap install diagon
```

I can provide Windows and Linux executables if needed. Feel free to ask for new features if you need something.

To get the documentation you can type:
```bash
diagon help
```

To get the documentation for the Math module, you can type:
```bash
diagon Math help
```

Most likely, you want to use something like:
```bash
cat input | diagon Math --style=latex
```
Or
```
diagon Math --style=latex -- "inline formula"
```

(It might be slightly different, I can't check locally at the moment)

Thanks for filling this question!

**Comment by Pomax** [comment]
> Note that it can output latex, but not take latex as input.

Dang, I completely missed that =(

But thanks for the detailed answer!

**Comment by Pomax** [comment]
(did not mean to press "close" >_>;;)
