### ISSUE TITLE
provide a downloadable offline page.

### ISSUE THREAD

**Issue by ArthurSonzogni** [ArthurSonzogni/Diagon#9]
The website is already available offline thanks to service worker, but users might also want an offline page to download.

**Comment by iyuter** [comment]
Please compile for older, JS-only compatible web-browsers, if it's not difficult

**Comment by ArthurSonzogni** [comment]
This is C++ code compiled toward WebAssembly.

I guess I could used tools to compile webAssembly toward JavaScript, but
this sounds a lot of works (~10days). I am not sure this is worth it, I am
not sure this would benefits a lot of users.

What kind of browsers do you use? What's your use case?

**Comment by iyuter** [comment]
Sorry, days of useless work are certainly not worth wasting. 
Just make it as a downloadable package, please

**Comment by ArthurSonzogni** [comment]
If the website is opened via a local file, then fetching the webassembly code would trigger this error:
```
Access to XMLHttpRequest at 'file:///home/sonzogna/programmation/real/Diagon/build_emscripten/diagon.wasm' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
```

Would it be good enough if I also provide the command to run a local server and open the page?
```
#! /bin/bash
python3 -m SimpleHTTPServer 8080
```

**Comment by iyutr** [comment]
Could you please share your current build, so I can test in Firefox/Palemoon by bypassing CORS? 
For other users it is helpful to know how to run a local Python server. Thank you for this program and for your diligence, perfecting it.

**Comment by ArthurSonzogni** [comment]
A build would look like this:
https://github.com/ArthurSonzogni/Diagon/suites/2305312146/artifacts/48367187

**Comment by iyutr** [comment]
It really works offline for me, without Pyton server, thank you !

**Comment by ArthurSonzogni** [comment]
I am closing this.

The downloadable offline page is produced in the release page:
https://github.com/ArthurSonzogni/Diagon/releases/

For instance:
https://github.com/ArthurSonzogni/Diagon/releases/download/v1.0.127/diagon-Web.zip
